* Notes for using Preact/React
** Module Importing 
*** Import Statements
    import defaultMember from "module-name";
    import * as name from "module-name";
    import { member } from "module-name";
    import { member as alias } from "module-name";
    import { member1 , member2 } from "module-name";
    import { member1 , member2 as alias2 , [...] } from "module-name";
    import defaultMember, { member [ , [...] ] } from "module-name";
    import defaultMember, * as name from "module-name";
    import "module-name";

    Webpack imports can be customised in the webpack.config.babel.js file.
    Updating the paths in resolve.modules

    Relative path imports as normal. General skip the path and use the name.
*** css imports
    @import 'path';

    can use ~ for home.

*** Libs 
    RequireJS format works fine, just import it all as an alias.
** Program Structure:
   index.js -> app -> compoments.
   
** Components. 
   Components use this.state to store. 
   Don't communicate to parents, lift data up a level and pass callbacks to the children
   to modify parent data.
   For JSX wrap variables etc in { }.
   Import libs as necessary
   
   Make sure to:
   import { h , Component } from 'preact';
   import { Link } from 'preact-router';
   import style from './style';
